### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by jimparis** [jabdoa2/smbus2_asyncio#3]
If any of the i2c operations raise an exception, self.lock remains locked and subsequent commands will hang.

**Comment by jabdoa2** [comment]
#4 should fix that. it is included in release 0.0.5. Or should we turn the locks into context managers?

**Comment by jimparis** [comment]
#1 does that.  Not sure if you can easily use a the lock's context manager without also switching to Python 3.5 syntax.

**Comment by jabdoa2** [comment]
Should be resolved by #7
